apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-sample
spec:
  replicas: 3
  selector:
    matchLabels:
        name: basic-sample
  template:
    metadata:
      labels:
        name: basic-sample
    spec:
      containers:
      - name: server
        image: dynatracek8s/basic-sample:<your-name>
        #env:
        #- name: NAME
        #  value: "John Doe"
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 8080
