apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontail
  name: frontail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontail
  template:
    metadata:
      labels:
        app: frontail
    spec:
      volumes:
      - name: frontail-storage
        persistentVolumeClaim:
          claimName: data-claim
      containers:
      - image: mthenw/frontail
        name: frontail
        ports:
        - containerPort: 9001
        command:
        - "/frontail/docker-entrypoint.sh"
        args:
        - "-t"
        - "default"
        - "-n"
        - "500"
        - "/data/history.log"
        volumeMounts:
        - mountPath: "/data"
          name: frontail-storage
        resources:
          requests:
            cpu: 300m
            memory: 400Mi
          limits:
            cpu: 300m
            memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontail
  name: frontail
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
    nodePort: 30080
  selector:
    app: frontail
  type: NodePort
